include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: 
    - build/**
    - lib/widget/traffic_charts.dart

  strong-mode:
    implicit-casts: true

linter:
  rules:
    - camel_case_types
